In [1]:
import pandas as pd
import numpy as np
import nltk as nlp
import sys
import json

from sklearn.neural_network import MLPClassifier as Model
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn import metrics
from nltk.corpus import stopwords

In [2]:
data = pd.read_csv('Snopes-data.csv')
X = data['Text']
y = data['Label']

In [5]:
vectorizer = TfidfVectorizer(sublinear_tf = True, min_df = 5, norm='l2', encoding='latin-1', ngram_range=(1, 2), stop_words='english', lowercase=False, max_features=1000)

In [6]:
features = vectorizer.fit_transform(X)

In [8]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3)
count_vect = CountVectorizer()
X_train_counts = count_vect.fit_transform(X_train)
tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)

In [9]:
classifier = Model()

In [10]:
classifier.fit(X_train_tfidf, y_train.values.ravel())

MLPClassifier()

In [11]:
X_test_counts = count_vect.transform(X_test)

In [12]:
prediction = classifier.predict(X_test_counts)

In [13]:
accuracy = metrics.accuracy_score(y_test, prediction)
accuracy

0.6476068101509798

In [14]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test, prediction))
print(confusion_matrix(y_test,prediction))

              precision    recall  f1-score   support

           0       0.43      0.99      0.60       818
           1       0.99      0.74      0.85       960
           2       0.94      0.30      0.45       558
           3       1.00      0.45      0.62       404
           4       0.98      0.39      0.56       373

    accuracy                           0.65      3113
   macro avg       0.87      0.57      0.62      3113
weighted avg       0.84      0.65      0.65      3113

[[808   0  10   0   0]
 [242 715   0   0   3]
 [392   0 166   0   0]
 [222   0   0 182   0]
 [224   4   0   0 145]]
